### ISSUE TITLE
How can I contact the developer for paid services ? 

### ISSUE THREAD

**Issue by MoAli980** [ahmadpak/ksa_vat#24]
How can I contact the developer for paid services ?

**Comment by nasirrr** [comment]
Are you looking for ZATCA phase 2? If yes, then comment your email id/whatsapp, I'll message you.

**Comment by MoAli980** [comment]
+966530872583
mm.alsaftty@gmail.com

**Comment by ahmadpak** [comment]
You can find our details on our website.
https://havenir.com
